#!/bin/bash

# Env Name
ENV_NAME="theLungPr"

# Verify conda availability
if ! command -v conda &> /dev/null; then
    echo "Conda is not installed or is not in PATH. Please install Miniconda or Anaconda first."
    exit 1
fi

# Create conda env with Python 3.10 
echo "Creating Conda environment: $ENV_NAME"
conda create -y -n $ENV_NAME python=3.10

# Install packages INSIDE the environment using conda run
echo "Installing packages in $ENV_NAME"
conda run -n $ENV_NAME pip install \
    absl-py \
    adjusttext \
    aiohappyeyeballs \
    aiohttp \
    aiosignal \
    altair \
    anndata \
    anndata2ri \
    ant \
    anyio \
    appdirs \
    arboreto \
    argon2-cffi \
    argon2-cffi-bindings \
    arpack \
    array-api-compat \
    arrow \
    arviz \
    asttokens \
    astunparse \
    async-lru \
    async-timeout \
    attrs \
    babel \
    backcall \
    beautifulsoup4 \
    binaryornot \
    biofluff \
    biopython \
    biothings-client \
    blas \
    bleach \
    bokeh \
    boltons \
    bottleneck \
    brotli \
    brotli-bin \
    brotli-python \
    bzip2 \
    ca-certificates \
    cellphonedb \
    celltypist \
    certifi \
    cffi \
    cfgv \
    chardet \
    charset-normalizer \
    chex \
    click \
    cloudpickle \
    colorama \
    colorcet \
    comm \
    configparser \
    contextlib2 \
    contourpy \
    cookiecutter \
    ctxcore \
    curlify \
    custom-inherit \
    cycler \
    cython \
    cytoolz \
    dask \
    dask-expr \
    debugpy \
    decorator \
    decoupler \
    defusedxml \
    dill \
    diskcache \
    distlib \
    distributed \
    dm-tree \
    dnspython \
    docopt \
    docrep \
    doubletdetection \
    elasticsearch \
    entrypoints \
    equinox \
    ete3 \
    etils \
    et-xmlfile \
    exceptiongroup \
    executing \
    fastcluster \
    fastjsonschema \
    fbpca \
    fcsparser \
    feather-format \
    filelock \
    flatbuffers \
    flax \
    fonttools \
    fqdn \
    freetype \
    frozendict \
    frozenlist \
    fsspec \
    ftpretty \
    future \
    gast \
    gdown \
    genomepy \
    geosketch \
    get-annotations \
    gimmemotifs \
    glpk \
    gmp \
    goatools \
    google-pasta \
    gprofiler-official \
    grpcio \
    gseapy \
    h11 \
    h5netcdf \
    h5py \
    harmony-py \
    harmonypy \
    heapdict \
    htseq \
    httpcore \
    httpx \
    hyperopt \
    icu \
    identify \
    idna \
    importlib-metadata \
    importlib_metadata \
    importlib_resources \
    inflect \
    iniconfig \
    interlap \
    ipykernel \
    ipython \
    ipywidgets \
    isoduration \
    iteround \
    jax \
    jax-cuda12-pjrt \
    jax-cuda12-plugin \
    jaxlib \
    jaxopt \
    jaxtyping \
    jedi \
    jinja2 \
    joblib \
    json5 \
    jsonpickle \
    jsonpointer \
    jsonschema \
    jsonschema-specifications \
    jupyter \
    jupyter-client \
    jupyter-console \
    jupyter_core \
    jupyter-events \
    jupyterlab \
    jupyterlab-pygments \
    jupyterlab-server \
    jupyterlab-widgets \
    jupyter-lsp \
    jupyter-server \
    jupyter-server-terminals \
    keras \
    kiwisolver \
    ktplotspy \
    lcms2 \
    ld_impl_linux-64 \
    legacy-api-wrap \
    leidenalg \
    lerc \
    liana \
    libblas \
    libbrotlicommon \
    libbrotlidec \
    libbrotlienc \
    libclang \
    libdeflate \
    libffi \
    libgcc \
    _libgcc_mutex \
    libgcc-ng \
    libgfortran \
    libgfortran5 \
    libgfortran-ng \
    libiconv \
    libjpeg-turbo \
    liblapack \
    libnsl \
    libpng \
    libsodium \
    libsqlite \
    libstdcxx \
    libstdcxx-ng \
    libtiff \
    libuuid \
    libwebp-base \
    libxcb \
    libxcrypt \
    libxml2 \
    libzlib \
    lightning \
    lightning-utilities \
    lineax \
    llvmlite \
    llvm-openmp \
    locket \
    logomaker \
    loguru \
    loompy \
    louvain \
    lxml \
    lz4 \
    lz4-c \
    markdown \
    markdown-it-py \
    markupsafe \
    matplotlib-base \
    matplotlib-inline \
    mdurl \
    mellon \
    mistune \
    mizani \
    mkl \
    mkl_fft \
    mkl_random \
    mkl-service \
    ml-collections \
    ml-dtypes \
    more-itertools \
    mpmath \
    msgpack \
    msgpack-python \
    mudata \
    multicoretsne \
    multidict \
    multipledispatch \
    multiprocessing-on-dill \
    munkres \
    muon \
    mygene \
    mysql-connector-python \
    namex \
    narwhals \
    natsort \
    nbclient \
    nbconvert \
    nbformat \
    ncurses \
    nest-asyncio \
    networkx \
    nodeenv \
    norns \
    nose \
    notebook \
    notebook-shim \
    numba \
    numexpr \
    numpy \
    numpy-base \
    numpy-groupies \
    numpyro \
    nvidia-cublas-cu12 \
    nvidia-cuda-cupti-cu12 \
    nvidia-cuda-nvcc-cu12 \
    nvidia-cuda-nvrtc-cu12 \
    nvidia-cuda-runtime-cu12 \
    nvidia-cudnn-cu12 \
    nvidia-cufft-cu12 \
    nvidia-curand-cu12 \
    nvidia-cusolver-cu12 \
    nvidia-cusparse-cu12 \
    nvidia-nccl-cu12 \
    nvidia-nvjitlink-cu12 \
    nvidia-nvtx-cu12 \
    omnipath \
    openjdk \
    openjpeg \
    _openmp_mutex \
    openpyxl \
    openssl \
    optax \
    opt-einsum \
    optree \
    orbax-checkpoint \
    ott-jax \
    overrides \
    packaging \
    palantir \
    palettable \
    pandas \
    pandocfilters \
    parso \
    partd \
    pathlib \
    patsy \
    pertpy \
    pexpect \
    phenograph \
    pickleshare \
    pillow \
    pip \
    platformdirs \
    plotnine \
    plottable \
    pluggy \
    ply \
    pockets \
    pre-commit \
    progressbar2 \
    prometheus-client \
    prompt-toolkit \
    prompt_toolkit \
    protobuf \
    psutil \
    ptyprocess \
    pure_eval \
    pyarrow \
    pyarrow-hotfix \
    pybedtools \
    pybigwig \
    pycirclize \
    pycparser \
    pydeseq2 \
    pydot \
    pyfaidx \
    pygam \
    pygments \
    pymde \
    pymongo \
    pynndescent \
    pyomo \
    pyparsing \
    pypi-latest \
    pypng \
    pyqt5 \
    pyqt5-qt5 \
    pyqt5-sip \
    pyro-api \
    pyro-ppl \
    pysam \
    pyscenic \
    pysocks \
    pytest \
    python \
    python_abi \
    python-circos \
    python-dateutil \
    python-dotenv \
    python-igraph \
    python-json-logger \
    python-lmdb \
    python-louvain \
    python-slugify \
    python-tzdata \
    python-utils \
    pytorch-lightning \
    pytz \
    pyvis \
    pyyaml \
    pyzmq \
    qnorm \
    questionary \
    ray \
    readline \
    referencing \
    reportlab \
    requests \
    rfc3339-validator \
    rfc3986-validator \
    rich \
    rpds-py \
    rpy2 \
    scanpy \
    sccoda \
    scib-metrics \
    scikit-learn \
    scikit-misc \
    scipy \
    sc-toolbox \
    scvi-tools \
    seaborn \
    send2trash \
    session-info \
    setuptools \
    shapely \
    six \
    slingshot \
    sniffio \
    sortedcontainers \
    soupsieve \
    sparsecca \
    sphinxcontrib-napoleon \
    stack-data \
    statsmodels \
    stdlib-list \
    sympy \
    tabulate \
    tbb \
    tblib \
    tensorboard \
    tensorboard-data-server \
    tensorflow \
    tensorflow-io-gcs-filesystem \
    tensorflow-probability \
    tensorstore \
    termcolor \
    terminado \
    texttable \
    text-unidecode \
    threadpoolctl \
    tinycss2 \
    tk \
    tomli \
    toolz \
    torch \
    torchmetrics \
    torchvision \
    tornado \
    toyplot \
    toytree \
    tqdm \
    traitlets \
    triton \
    typeguard \
    types-python-dateutil \
    typing_extensions \
    tzdata \
    tzlocal \
    umap-learn \
    unicodedata2 \
    uri-template \
    urllib3 \
    velocyto \
    virtualenv \
    wcwidth \
    webcolors \
    webencodings \
    websocket-client \
    werkzeug \
    wheel \
    widgetsnbextension \
    wrapt \
    xarray \
    xarray-einstats \
    xdg \
    xlrd \
    xlsxwriter \
    xxhash \
    xyzservices \
    xz \
    yaml \
    yarl \
    zeromq \
    zict \
    zipp \
    zstd

# Add the kernel to Jupyter
echo "Installing the environment as kernel to Jupyter"
conda run -n $ENV_NAME python -m ipykernel install --user --name $ENV_NAME --display-name "Python ($ENV_NAME)"

echo "Done. '$ENV_NAME' kernel is now available in Jupyter."
